# Generated by Django 6.0 on 2025-12-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский / Russian'), ('es', 'Español / Spanish'), ('zh', '中文 / Chinese'), ('ar', 'العربية / Arabic'), ('hi', 'हिन्दी / Hindi'), ('pt', 'Português / Portuguese'), ('fr', 'Français / French'), ('de', 'Deutsch / German'), ('ja', '日本語 / Japanese'), ('bn', 'বাংলা / Bengali'), ('pa', 'ਪੰਜਾਬੀ / Punjabi'), ('ur', 'اردو / Urdu'), ('id', 'Bahasa Indonesia / Indonesian'), ('ms', 'Bahasa Melayu / Malay'), ('vi', 'Tiếng Việt / Vietnamese'), ('ko', '한국어 / Korean'), ('it', 'Italiano / Italian'), ('tr', 'Türkçe / Turkish'), ('fa', 'فارسی / Persian'), ('sw', 'Kiswahili / Swahili'), ('ta', 'தமிழ் / Tamil'), ('mr', 'मराठी / Marathi'), ('te', 'తెలుగు / Telugu'), ('th', 'ไทย / Thai'), ('gu', 'ગુજરાતી / Gujarati'), ('kn', 'ಕನ್ನಡ / Kannada'), ('ml', 'മലയാളം / Malayalam'), ('or', 'ଓଡ଼ିଆ / Odia'), ('ne', 'नेपाली / Nepali'), ('am', 'አማርኛ / Amharic'), ('he', 'עברית / Hebrew'), ('el', 'Ελληνικά / Greek'), ('hu', 'Magyar / Hungarian'), ('nl', 'Nederlands / Dutch'), ('pl', 'Polski / Polish'), ('ro', 'Română / Romanian'), ('uk', 'Українська / Ukrainian'), ('sv', 'Svenska / Swedish'), ('fi', 'Suomi / Finnish'), ('cs', 'Čeština / Czech'), ('da', 'Dansk / Danish'), ('no', 'Norsk / Norwegian'), ('sr', 'Српски / Serbian'), ('hr', 'Hrvatski / Croatian'), ('sk', 'Slovenčina / Slovak'), ('bg', 'Български / Bulgarian'), ('lt', 'Lietuvių / Lithuanian'), ('lv', 'Latviešu / Latvian'), ('an', 'Any Language')], default='an', help_text='введите код языка по стандарту ISO 639-1', max_length=2),
        ),
    ]
