# Generated by Django 6.0 on 2025-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('о', 'Обслуживание'), ('в', 'В использовании'), ('д', 'Доступна'), ('з', 'Зарезервирована')], default='о', help_text='Наличие книги', max_length=1),
        ),
    ]
