# Generated by Django 6.0 on 2026-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Обслуживание'), ('o', 'В использовании'), ('a', 'Доступна'), ('r', 'Зарезервирована')], default='a', help_text='Наличие книги', max_length=1),
        ),
    ]
